### ISSUE TITLE
Bug: Key waiting state blocks hiding monitors

### ISSUE THREAD

**Issue by pushfoo** [JohnEarnest/c-octo#14]
~~I'll make a PR soon.~~ ada0845

## Affected
octo-run, octo-de

## Steps to replicate
1. Run code below
```
:monitor v0 4

: main
  i := circle
  plane 1
  loop
    sprite v0 v1 8
    v0 += 3
    v1 += 5
    v2 := key
  again

: circle
 0x3C 0x7E 0xFF 0xFF 0xFF 0xFF 0x7E 0x3C
```
2. press m to engage monitor
3. press m to disengage monitor
4. monitor does not disengage

## Expected behavior
Monitors turn off

## Actual Behavior
Monitors don't turn off

**Comment by JohnEarnest** [comment]
Oh, oops. I didn't catch that you were already working up a fix.

**Comment by pushfoo** [comment]
That was fast, lol. ada0845 fixes the issue locally on Debian 11 x86_64.

**Comment by JohnEarnest** [comment]
The whole lazy-repaint thing made a big difference in performance when using a software renderer on some slower machines like the XO-1 I used for testing, but boy is it a recipe for annoying corner cases.
