### ISSUE TITLE
A few errors whilist building

### ISSUE THREAD

**Issue by KrzysztofJeszke** [JohnEarnest/c-octo#2]
`src/octo_de.c: In function ‘render_text_editor’:
src/octo_de.c:517:69: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size between 230 and 250 [-Werror=format-truncation=]
  517 |       snprintf(state.text_status,sizeof(state.text_status),"(%d:%d) %s",prog->error_line+1,prog->error_pos+1,prog->error);state.text_err=1;
      |                                                                     ^~
src/octo_de.c:517:7: note: ‘snprintf’ output between 7 and 4122 bytes into a destination of size 256
  517 |       snprintf(state.text_status,sizeof(state.text_status),"(%d:%d) %s",prog->error_line+1,prog->error_pos+1,prog->error);state.text_err=1;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c:689:65: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 250 [-Werror=format-truncation=]
  689 |     snprintf(state.text_status,sizeof(state.text_status),"Find: %s",trimmed); state.text_err=0;
      |                                                                 ^~  ~~~~~~~
src/octo_de.c:689:5: note: ‘snprintf’ output between 7 and 262 bytes into a destination of size 256
  689 |     snprintf(state.text_status,sizeof(state.text_status),"Find: %s",trimmed); state.text_err=0;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c: In function ‘open_choose’:
src/octo_de.c:1307:83: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 232 [-Werror=format-truncation=]
 1307 |     snprintf(state.text_status,sizeof(state.text_status),"Imported CHIP-8 binary '%s'",entry->name);state.text_err=0;
      |                                                                                   ^~
src/octo_de.c:1307:5: note: ‘snprintf’ output between 26 and 4121 bytes into a destination of size 256
 1307 |     snprintf(state.text_status,sizeof(state.text_status),"Imported CHIP-8 binary '%s'",entry->name);state.text_err=0;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c:1287:106: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 235 [-Werror=format-truncation=]
 1287 | if(stat(filename,&st)!=0){snprintf(state.text_status,sizeof(state.text_status),"Unable to open file '%s'",entry->name);state.text_err=1;return;}
      |                                                                                                      ^~

src/octo_de.c:1287:31: note: ‘snprintf’ output between 23 and 4118 bytes into a destination of size 256
 1287 |     if(stat(filename,&st)!=0){snprintf(state.text_status,sizeof(state.text_status),"Unable to open file '%s'",entry->name);state.text_err=1;return;}
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c:1323:72: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 243 [-Werror=format-truncation=]
 1323 |     snprintf(state.text_status,sizeof(state.text_status),"Opened file '%s'",entry->name);state.text_err=0;
      |                                                                        ^~
src/octo_de.c:1323:5: note: ‘snprintf’ output between 15 and 4110 bytes into a destination of size 256
 1323 |     snprintf(state.text_status,sizeof(state.text_status),"Opened file '%s'",entry->name);state.text_err=0;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c:1312:106: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 235 [-Werror=format-truncation=]
 1312 | if(stat(filename,&st)!=0){snprintf(state.text_status,sizeof(state.text_status),"Unable to open file '%s'",entry->name);state.text_err=1;return;}
      |                                                                                                      ^~

src/octo_de.c:1312:31: note: ‘snprintf’ output between 23 and 4118 bytes into a destination of size 256
 1312 |     if(stat(filename,&st)!=0){snprintf(state.text_status,sizeof(state.text_status),"Unable to open file '%s'",entry->name);state.text_err=1;return;}
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c:1337:76: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 239 [-Werror=format-truncation=]
 1337 |     snprintf(state.text_status,sizeof(state.text_status),"Opened octocart '%s'",entry->name);state.text_err=0;
      |                                                                            ^~
src/octo_de.c:1337:5: note: ‘snprintf’ output between 19 and 4114 bytes into a destination of size 256
 1337 |     snprintf(state.text_status,sizeof(state.text_status),"Opened octocart '%s'",entry->name);state.text_err=0;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c:1329:86: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 231 [-Werror=format-truncation=]
 1329 |       snprintf(state.text_status,sizeof(state.text_status),"Unable to read octocart '%s'",entry->name);state.text_err=1;
      |                                                                                      ^~
src/octo_de.c:1329:7: note: ‘snprintf’ output between 27 and 4122 bytes into a destination of size 256
 1329 |       snprintf(state.text_status,sizeof(state.text_status),"Unable to read octocart '%s'",entry->name);state.text_err=1;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c: In function ‘save_file’:
src/octo_de.c:1375:73: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 240 [-Werror=format-truncation=]
 1375 |   snprintf(state.text_status,sizeof(state.text_status),"Saved octocart '%s'",state.open_name);state.text_err=0;
      |                                                                         ^~   ~~~~~~~~~~~~~~~
src/octo_de.c:1375:3: note: ‘snprintf’ output between 18 and 4113 bytes into a destination of size 256
 1375 |   snprintf(state.text_status,sizeof(state.text_status),"Saved octocart '%s'",state.open_name);state.text_err=0;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/octo_de.c:1367:85: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 230 [-Werror=format-truncation=]
 1367 |     snprintf(state.text_status,sizeof(state.text_status),"Unable to write octocart '%s'",state.open_name);state.text_err=1;
      |                                                                                     ^~   ~~~~~~~~~~~~~~~
src/octo_de.c:1367:5: note: ‘snprintf’ output between 28 and 4123 bytes into a destination of size 256
 1367 |     snprintf(state.text_status,sizeof(state.text_status),"Unable to write octocart '%s'",state.open_name);state.text_err=1;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:42: ide] Error 1`
Removing -Werror from the makefile fixed it for me. A temporary fix that is.

**Comment by JohnEarnest** [comment]
I assume you're using a recent version of GCC? It's very difficult to investigate this kind of issue if you don't make note of your OS/Compiler versions.

At any rate, these errors are spurious- `snprintf()` is being used to _explicitly_ truncate status bar descriptions. Try adding `-Wno-format-truncation` to the Makefile. With your confirmation, I'll commit the change.

**Comment by KrzysztofJeszke** [comment]
That did it, thanks!
